config/routes.rb
Rails.application.routes.draw do

  resources :items do
  member do
    get 'show_image'
   
  end
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
	attr_accessor :image_full


  #validate do

  #  if image_full.present?
  #    errors[:base] << I18n.t('alert...') unless image_full.image_type === "image/jpeg"
  #  end

 # end

#def self.create_items_by(item_params)

#  return false if item_params[:image].nil?


  #item.transaction do 

#    item_params[:image].each do |item|
#      new_item = item.new(item: item_params[:item], image: item)
#      return false unless new_item.save!
#    end
#  end

#  true
end

app/models/item_bak.rb
class Item < ApplicationRecord
	attr_accessor :image_full
    
  def self.create_items_by(item_params)


  return false if item_params[:image].nil?

  Item.transaction do 

    item_params[:image].each do |item|
      new_item = Item.new(item: item_params[:item], image: item)
      return false unless new_item.save!
    end
  end

  true
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show_image, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
    def show_image
    @item = Item.find(params[:id])
    send_data @item.image, :type => 'image/jpeg', :disposition => 'inline'
    end


    def show
       @item = Item.find(params[:id])
    end






  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if image = params[:item][:image]
        @item.image = image.read
          @item.image_full = image
      end

    if @item.save
      format.html { redirect_to @item, notice: 'Item was successfully created.' }
       # format.json { render :show, status: :created, location: @item }
    else
        format.html { render :new }
        #format.json { render json: @item.errors, status: :unprocessable_entity }
     end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      #params.require(:item).permit(:item, :image, :image2 )　
      params.require(:item).permit( :item, {image: []})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for( @item, :html => { :multipart => true }) do |f| %>
 
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item %>
    <%= f.text_field :item, id: :item_item %>
  </div>

  <div class="field">
    <%= f.label :画像１ %>
    <%= f.file_field :image, :multipule => true, :class => 'file_field' %>
  </div>

  <div class="field">
    <%= f.label :画像２%>
   <%= f.file_field :image2, :multipule => true, :class => 'file_field' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.item %></td>
        <td>  <%= image_tag show_image_item_path(item.id), :size =>'50x50'%></td>
        <td>  <%= image_tag show_image_item_path(item.id), :size =>'50x50'%></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

  <td>  <%= image_tag show_image_item_path(@item.id), :size =>'200x300'%></td>

<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleUp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>